### PR TITLE
TikTok black ring fix

### PR DESCRIPTION
**Pull request by akakalle**
Fixes the black ring around the TikTok icon. Recreate by using TikTok icon with bgColor="white" fgColor="black".

As of pbozyk's solution here: https://github.com/jaketrent/react-social-icons/issues/146

### CODE REVIEW

**Comment by akakalle** [comment]
Recreate by using bgColor="white" fgColor="black"

**Review by pbozyk — APPROVED** [review]

**Comment by lizzieshipwreck** [comment]
can someone merge this? The tik tok ring is making this package literally unusable for me

**Comment by couetilc** [comment]
hi @akakalle, this has been addressed in [v6 of react-social-icons](https://www.npmjs.com/package/react-social-icons)

CC @lizzieshipwreck

**Comment by akakalle** [comment]
@couetilc great thanks for the update!

**Pull request closed without merging**
